name: Build executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Wemod-Patcher.sln

      - name: Build proxy DLL
        shell: cmd
        run: |
          cd tools\asar-fuses-bypass
          cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build-release --config Release

      - name: Find version.dll
        shell: powershell
        run: |
          Get-ChildItem -Path tools\asar-fuses-bypass -Filter version.dll -Recurse

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Wand Enhancer
        run: msbuild Wemod-Patcher.sln /p:Configuration=Release /p:RestorePackagesConfig=true

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Wand-Enhancer-v1.0.6.0
          path: |
            **/bin/Release/*.exe
            **/bin/Release/*.dll
