name: Build executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Wemod-Patcher.sln

      - name: Build
        run: dotnet build Wemod-Patcher.sln --configuration Release --no-restore

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Wand-Enhancer-v1.0.6.0
          path: |
            **/bin/Release/**
